#!/usr/local/bin/bash
# Project  Name: None
# File / Folder: /.bash/go
# File Language: sh
# Copyright (C): 2013 Liam Echlin
# First  Author: Liam Echlin
# First Created: 2013.02.02
# Last Modifier: Liam Echlin
# Last Modified: 2013.02.02

export GOROOT=/usr/local/go
export GOPATH=~/go
