#!/usr/bin/env bash

CODE_RED=$'\[\033[0;31m\]'
CODE_GREEN=$'\[\033[0;32m\]'
CODE_YELL=$'\[\033[0;33m\]'
CODE_NORM=$'\[\033[m\]'

if [ -e /sys/class/power_supply/BAT1/capacity ]; then
	BAT_LIFE=`cat /sys/class/power_supply/BAT1/capacity`
	[ "`cat /sys/class/power_supply/BAT1/status`" = "Charging" ]
	CHARGING=$?
else
	BAT_LIFE=`sysctl -n hw.acpi.battery.life`
	[ `sysctl -n hw.acpi.battery.time` -lt 0 ]
	CHARGING=$?
fi

if [ $BAT_LIFE -gt 50 ]; then
	echo -n $CODE_GREEN
elif [ $BAT_LIFE -gt 25 ]; then
	echo -n $CODE_YELL
else
	echo -n $CODE_RED
fi

echo -n $BAT_LIFE$CODE_NORM

if [ $CHARGING -eq 0 ]; then
	echo -n $CODE_GREEN+$CODE_NORM
else
	echo -n %
fi
