#!/bin/sh

EXCLUDES='CVS .* logs'

USAGE="Usage: "`basename $0`" [-cd?] [-x <pattern> ...] <directory> [directory]"


MD5="md5 -q"

while getopts cdx:? param; do
	case "$param" in
	c) DELETE= ;;
	d) DELETE=1 ;;
	x)
		set -o noglob
		EXCLUDES="$EXCLUDES $OPTARG"
		set +o noglob
	;;
	?)
		echo $USAGE
		spaces=`echo $(basename $0) | sed -e's/./ /g'`
		echo "`basename $0`"
		echo "$spaces -c: Show only changes (default)"
		echo "$spaces -d: Show only deleted files (note that changing the order of arguments will change the output)"
		echo "$spaces -x <pattern>: Exclude files matching <pattern> (multiple -x arguments are allowed)"
		exit
	;;
	esac
done
shift `expr $OPTIND - 1`

if [ $# -lt 1 ]; then
	echo $USAGE
	exit 2
fi

DIR1=$1
DIR2=$2

exclude_pattern=
set -o noglob
for pattern in $EXCLUDES; do
	exclude_pattern="$exclude_pattern -name $pattern -prune -o"
done
fileset=`find $DIR1 $exclude_pattern -type f -print`
set +o noglob

for file in $fileset; do
	rel_file=`echo $file | sed "s#^$1##"`
	if [ -e "$DIR2/$rel_file" -a -z "$DELETE" ]; then
		if [ "`$MD5 $DIR2/$rel_file`" != "`$MD5 $file`" ]; then
			echo "C $rel_file"
		fi
	elif [ "$DELETE" ]; then
		echo "D $rel_file"
	fi
done
