#!/bin/sh

BASE="$1"
LOCAL="$2"
REMOTE="$3"
MERGED="$4"

echo "{$REMOTE}"

vim -c"vert diffsplit $BASE" -c"tabe $LOCAL" -c"vert diffsplit $MERGED" -c"vert diffsplit $REMOTE" -c"tabe $BASE" -c"vert diffsplit $REMOTE" -- $LOCAL
