# 
# Project  Name: None
# File / Folder: Makefile
# File Language: make
# Copyright (C): 2005 Liam Bryan
# First  Author: Liam Bryan
# First Created: 2005.10.24 21:00:33
# Last Modifier: Liam Bryan
# Last Modified: 2005.10.24 21:04:43

CC = gcc

../bin/beeper: beeper.c
	$(CC) -O3 -o beeper beeper.c
	cp beeper ../bin/
